[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
disallow_untyped_defs = True
check_untyped_defs = True
# Silencing errors that are common when using JAX/Diffrax without full type stubs
disable_error_code = no-any-return, operator, arg-type
follow_imports = skip